name: Docker Image CI

on:
  push:
    tags: [ 'v*.*.*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check github ref
      run: echo "$GITHUB_REF"
    - name: Set tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test tag
      run: echo "$RELEASE_VERSION"
    - name: Build the Docker image
      env:
        RELEASE_TAG: ${{ steps.vars.output.tag }}
      run: docker build . --file Dockerfile -t "briankopp/aws-load-balancer-drain-wait:$RELEASE_TAG"
