name: Build and Push Docker for Tag

on:
  push:
    tags: [ 'v*.*.*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Docker Deploy
    steps:
    - uses: actions/checkout@v3
    - name: Set tag
      run: echo "IMAGE_NAME=\"briankopp/aws-load-balancer-drain-wait:${GITHUB_REF#refs/*/}\"" >> $GITHUB_ENV
    - name: Check username
      run: echo "${{ secrets.DOCKER_USERNAME }}"
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.0.0
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}
