name: Build and Push Docker for Tag

on:
  push:
    tags: [ 'v*.*.*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.0.0
      with:
        tags: "briankopp/aws-load-balancer-drain-wait:$RELEASE_VERSION"
