name: Build and Push Docker for Tag

on:
  push:
    tags: [ 'v*.*.*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build and push Docker image
      run: docker build . --file Dockerfile -t "briankopp/aws-load-balancer-drain-wait:$RELEASE_VERSION"
    - name: Push Docker image
      run: docker push "briankopp/aws-load-balancer-drain-wait:$RELEASE_VERSION"
